languageCode = "en-us"
title = "Contrail Collateral"
baseURL = "https://minkimipt.gitlab.io/hugo"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Reverse Engineering in Practice"
