languageCode = "en-us"
title = "Contrail Collateral"
baseURL = "codebuild-blog-bucket.s3-website-us-west-2.amazonaws.com"
canonifyURLs = true
theme = "cupper"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
    
[params]
description = "Reverse Engineering in Practice"
    
  [params.staticman]
  api = "https://minkimipt-staticman.herokuapp.com/v3/entry/gitlab/minkimipt/blog-comments/master/comments"
  enabled = true
  gitProvider = "gitlab"
  username = "minkimipt-staticman"
    
    [params.staticman.recaptcha]
    sitekey = "6LfNpsgZAAAAALm4RUToqxnT-MppTOsBEsijCxVH"
    secret = "ShsfOjZdwARINBeIRIprzGnbExYNA5LZ5WTT7+M1qmf2r3/HnpkwWvME2qZD0qswPvVNR5qjw26ebQ6pX//Kvu/1vLcQNDiFrjryRiYWCdjLb2hc8iyWyTYEEAm4rDWfUG/xDbwy9kLILxU+xzisgk8DfuGK9b06zlGoWBfYjY/tYLRl6ufHJhYqwa7te9UHTy02KzSqUVa4ASXenGmN9pckS92+bYuv+9rmqbPEKRF5sjZU3tZL2NgbFrDmopOn8tHVux//WMEdZeh4GciPhKTTjbTpKm3jXkjQ4Jya/IP2Hympye4g35ehkFfrdb7OgMu4TwlIAHfPLzE/H+IFKg=="
